<?php

return [
    'niveaux' => [
        ['code' => 'ms', 'label' => 'Petite Section', 'cycle' => 'maternelle'],
        ['code' => 'mm', 'label' => 'Moyenne Section', 'cycle' => 'maternelle'],
        ['code' => 'gs', 'label' => 'Grande Section', 'cycle' => 'maternelle'],
        ['code' => '1ap', 'label' => '1ere Annee Primaire', 'cycle' => 'primaire'],
        ['code' => '2ap', 'label' => '2eme Annee Primaire', 'cycle' => 'primaire'],
        ['code' => '3ap', 'label' => '3eme Annee Primaire', 'cycle' => 'primaire'],
        ['code' => '4ap', 'label' => '4eme Annee Primaire', 'cycle' => 'primaire'],
        ['code' => '5ap', 'label' => '5eme Annee Primaire', 'cycle' => 'primaire'],
        ['code' => '6ap', 'label' => '6eme Annee Primaire', 'cycle' => 'primaire'],
        ['code' => '1ac', 'label' => '1ere Annee College', 'cycle' => 'college'],
        ['code' => '2ac', 'label' => '2eme Annee College', 'cycle' => 'college'],
        ['code' => '3ac', 'label' => '3eme Annee College', 'cycle' => 'college'],
        ['code' => 'tc', 'label' => 'Tronc Commun', 'cycle' => 'lycee'],
        ['code' => '1bac', 'label' => '1ere Annee Baccalaureat', 'cycle' => 'lycee'],
        ['code' => '2bac', 'label' => '2eme Annee Baccalaureat', 'cycle' => 'lycee'],
    ],

    'filieres_by_niveau' => [
        'ms' => ['General'],
        'mm' => ['General'],
        'gs' => ['General'],
        '1ap' => ['General'],
        '2ap' => ['General'],
        '3ap' => ['General'],
        '4ap' => ['General'],
        '5ap' => ['General'],
        '6ap' => ['General'],
        '1ac' => ['General'],
        '2ac' => ['General'],
        '3ac' => ['General'],
        'tc' => ['TC Scientifique', 'TC Technologique', 'TC Lettres'],
        '1bac' => [
            'Sciences Experimentales - SVT (Francais)',
            'Sciences Experimentales - SVT (Arabe)',
            'Sciences Experimentales - Physique-Chimie (Francais)',
            'Sciences Experimentales - Physique-Chimie (Arabe)',
            'Sciences Mathematiques A (Francais)',
            'Sciences Mathematiques A (Arabe)',
            'Sciences Mathematiques B (Francais)',
            'Sciences Mathematiques B (Arabe)',
            'Sciences et Technologies Electrique (Francais)',
            'Sciences et Technologies Electrique (Arabe)',
            'Sciences et Technologies Mecanique (Francais)',
            'Sciences et Technologies Mecanique (Arabe)',
            'Lettres et Sciences Humaines',
            'Sciences Economiques',
        ],
        '2bac' => [
            'Sciences Experimentales - SVT (Francais)',
            'Sciences Experimentales - SVT (Arabe)',
            'Sciences Experimentales - Physique-Chimie (Francais)',
            'Sciences Experimentales - Physique-Chimie (Arabe)',
            'Sciences Mathematiques A (Francais)',
            'Sciences Mathematiques A (Arabe)',
            'Sciences Mathematiques B (Francais)',
            'Sciences Mathematiques B (Arabe)',
            'Sciences et Technologies Electrique (Francais)',
            'Sciences et Technologies Electrique (Arabe)',
            'Sciences et Technologies Mecanique (Francais)',
            'Sciences et Technologies Mecanique (Arabe)',
            'Lettres et Sciences Humaines',
            'Sciences Economiques',
        ],
    ],

    'pricing_by_niveau_filiere' => [
        'ms' => ['General' => 900],
        'mm' => ['General' => 950],
        'gs' => ['General' => 1000],
        '1ap' => ['General' => 1200],
        '2ap' => ['General' => 1200],
        '3ap' => ['General' => 1300],
        '4ap' => ['General' => 1300],
        '5ap' => ['General' => 1400],
        '6ap' => ['General' => 1400],
        '1ac' => ['General' => 1600],
        '2ac' => ['General' => 1700],
        '3ac' => ['General' => 1800],
        'tc' => [
            'TC Scientifique' => 2100,
            'TC Technologique' => 2100,
            'TC Lettres' => 1900,
        ],
        '1bac' => [
            'Sciences Experimentales - SVT (Francais)' => 2500,
            'Sciences Experimentales - SVT (Arabe)' => 2500,
            'Sciences Experimentales - Physique-Chimie (Francais)' => 2500,
            'Sciences Experimentales - Physique-Chimie (Arabe)' => 2500,
            'Sciences Mathematiques A (Francais)' => 2600,
            'Sciences Mathematiques A (Arabe)' => 2600,
            'Sciences Mathematiques B (Francais)' => 2600,
            'Sciences Mathematiques B (Arabe)' => 2600,
            'Sciences et Technologies Electrique (Francais)' => 2450,
            'Sciences et Technologies Electrique (Arabe)' => 2450,
            'Sciences et Technologies Mecanique (Francais)' => 2450,
            'Sciences et Technologies Mecanique (Arabe)' => 2450,
            'Lettres et Sciences Humaines' => 2200,
            'Sciences Economiques' => 2300,
        ],
        '2bac' => [
            'Sciences Experimentales - SVT (Francais)' => 3000,
            'Sciences Experimentales - SVT (Arabe)' => 3000,
            'Sciences Experimentales - Physique-Chimie (Francais)' => 3000,
            'Sciences Experimentales - Physique-Chimie (Arabe)' => 3000,
            'Sciences Mathematiques A (Francais)' => 3200,
            'Sciences Mathematiques A (Arabe)' => 3200,
            'Sciences Mathematiques B (Francais)' => 3200,
            'Sciences Mathematiques B (Arabe)' => 3200,
            'Sciences et Technologies Electrique (Francais)' => 2950,
            'Sciences et Technologies Electrique (Arabe)' => 2950,
            'Sciences et Technologies Mecanique (Francais)' => 2950,
            'Sciences et Technologies Mecanique (Arabe)' => 2950,
            'Lettres et Sciences Humaines' => 2400,
            'Sciences Economiques' => 2700,
        ],
    ],

    'matieres' => [
        ['nom' => 'Mathematiques', 'coefficient' => 5],
        ['nom' => 'Physique Chimie', 'coefficient' => 4],
        ['nom' => 'Sciences de la Vie et de la Terre', 'coefficient' => 4],
        ['nom' => 'Arabe', 'coefficient' => 4],
        ['nom' => 'Francais', 'coefficient' => 4],
        ['nom' => 'Anglais', 'coefficient' => 3],
        ['nom' => 'Espagnol', 'coefficient' => 2],
        ['nom' => 'Histoire Geographie', 'coefficient' => 3],
        ['nom' => 'Philosophie', 'coefficient' => 2],
        ['nom' => 'Informatique', 'coefficient' => 3],
        ['nom' => 'Education Islamique', 'coefficient' => 2],
        ['nom' => 'Education Physique', 'coefficient' => 2],
        ['nom' => 'Arts Plastiques', 'coefficient' => 1],
        ['nom' => 'Economie Generale', 'coefficient' => 3],
        ['nom' => 'Comptabilite et Math Financieres', 'coefficient' => 3],
        ['nom' => 'Science de l Ingenieur', 'coefficient' => 4],
        ['nom' => 'Technologie', 'coefficient' => 2],
        ['nom' => 'Communication et Soft Skills', 'coefficient' => 1],
    ],
];
